remote_theme: jekyll/minima

title: IBEX Micrcoscopy Imaging

header_pages:
  - index.md
  - roadmap.md
  - data_and_software.md
  - publications.md
  - q_and_a.md
  - contributing.md


minima:
  skin: classic

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

