theme: minima

title: IBEX Micrcoscopy Imaging

banner: ibex_banner.png

header_pages:
  - index.md
  - roadmap.md
  - data_and_software.md
  - publications.md
  - q_and_a.md
  - steering_committee.md

minima:
  skin: solarized

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

